import { INodeProperties } from 'n8n-workflow';
import { createField } from './common/fields';

export const campaignOperations: INodeProperties[] = [
  createField({
    displayName: 'Operation',
    name: 'operation',
    noDataExpression: true,
    type: 'options',
    resource: 'campaign',
    default: '',
    optionsList: [
      { name: 'Add Tag', value: 'addTag', action: 'Add tag to campaign', description: 'Add a tag to a campaign' },
      { name: 'Archive', value: 'archive', action: 'Archive campaign', description: 'Archive a campaign' },
      { name: 'Copy', value: 'copy', action: 'Copy campaign', description: 'Copy a campaign' },
      { name: 'Create', value: 'create', action: 'Create campaign', description: 'Create a new campaign' },
      { name: 'Delete', value: 'delete', action: 'Delete campaign', description: 'Delete a campaign permanently' },
      { name: 'Get', value: 'getById', action: 'Get campaign', description: 'Retrieve a campaign' },
      { name: 'Get Many', value: 'getMany', action: 'Get many campaigns', description: 'Retrieve a list of campaigns' },
      { name: 'Get Statistics', value: 'getStats', action: 'Get campaign statistics', description: 'Retrieve statistics for a campaign' },
      { name: 'Pause', value: 'pause', action: 'Pause campaign', description: 'Pause a campaign' },
      { name: 'Remove Prospect', value: 'removeProspect', action: 'Remove prospect from campaign', description: 'Remove a prospect from a campaign' },
      { name: 'Remove Tag', value: 'removeTag', action: 'Remove tag from campaign', description: 'Remove a tag from a campaign' },
      { name: 'Start', value: 'start', action: 'Start campaign', description: 'Start a campaign' },
      { name: 'Unarchive', value: 'unarchive', action: 'Unarchive campaign', description: 'Unarchive a campaign' },
      { name: 'Update', value: 'update', action: 'Update campaign', description: 'Update a campaign' },
    ],
  }),
];

export const campaignFields: INodeProperties[] = [

  createField({
    displayName: 'Page',
    name: 'page',
    type: 'number',
    default: 1,
    resource: 'campaign',
    operations: ['getMany'],
  }),

  createField({
    displayName: 'Limit',
    name: 'limit',
    type: 'number',
				typeOptions: {
					minValue: 1,
				},
				description: 'Max number of results to return',
    default: 50,
    resource: 'campaign',
    operations: ['getMany'],
  }),

  createField({
    displayName: 'Starting After',
    name: 'startingAfter',
    type: 'number',
    default: 0,
    description: 'Cursor for next page (optional, for cursor-based pagination)',
    resource: 'campaign',
    operations: ['getMany'],

  }),

  createField({
    displayName: 'Simplify',
    name: 'simplify',
    type: 'boolean',
    default: true,
    description: 'Whether to return a simplified version of the response instead of the raw data',
    resource: 'campaign',
    operations: ['getMany'],
  }),

  createField({
    displayName: 'Include Archived',
    name: 'includeArchived',
    type: 'boolean',
    default: false,
    description: 'Whether to include archived campaigns in the results',
    resource: 'campaign',
    operations: ['getMany'],
  }),

  createField({
    displayName: 'Status',
    name: 'status',
    type: 'options',
    options: [
      { name: 'Any', value: '' },
      { name: 'Running', value: 'running' },
      { name: 'Paused', value: 'paused' },
      { name: 'Draft', value: 'draft' },
      { name: 'Completed', value: 'completed' },
      { name: 'Archived', value: 'archived' },
      { name: 'Scheduled', value: 'scheduled' },
      { name: 'Preparing', value: 'preparing' },
    ],
    default: '',
    description: 'Filter campaigns by status',
    resource: 'campaign',
    operations: ['getMany'],
  }),

  createField({
    displayName: 'Campaign',
    name: 'campaignId',
    type: 'resourceLocator',
    default: { mode: 'list', value: '' },
    description: 'Select a campaign from the list or enter its ID',
    resource: 'campaign',
    operations: ['getById', 'delete', 'update', 'start', 'pause', 'getSequences', 'createSequences', 'copy', 'getStats', 'archive', 'unarchive', 'removeProspect', 'addTag', 'removeTag'],
    modes: [
      {
        displayName: 'From list',
        name: 'list',
        type: 'list',
        placeholder: 'Select a campaign...',
        typeOptions: {
          searchListMethod: 'searchCampaigns',
          searchable: true,
          searchFilterRequired: false,
        },
      },
      {
        displayName: 'By ID',
        name: 'id',
        type: 'string',
        placeholder: 'e.g. 1234',
        validation: [
          {
            type: 'regex',
            properties: {
              regex: '^\\d+$',
              errorMessage: 'Only numeric IDs are allowed',
            },
          },
        ],
      },
    ],
  }),

  createField({
    displayName: 'Name',
    name: 'name',
    type: 'string',
    default: '',
    description: 'Campaign display name for identification and organization; maximum 256 characters',
    resource: 'campaign',
    operations: ['create'],
    required: true,
  }),

  createField({
    displayName: 'Name',
    name: 'name',
    type: 'string',
    default: '',
    description: 'Campaign display name for identification and organization; maximum 256 characters',
    resource: 'campaign',
    operations: ['copy'],
  }),

  createField({
    displayName: 'Date Start',
    name: 'dateStart',
    type: 'string',
    default: '',
    placeholder: 'e.g. 2026-01-15',
    description: 'Optional. The start date (inclusive) for the statistics data range. Accepts ISO 8601 format: yyyy-MM-dd or yyyy-MM-ddTHH:mm:ss.fffZ (Z is optional, always interpreted as UTC). If not provided, defaults to the campaign creation date.',
    resource: 'campaign',
    operations: ['getStats'],

  }),

  createField({
    displayName: 'Date End',
    name: 'dateEnd',
    type: 'string',
    default: '',
    placeholder: 'e.g. 2026-01-15',
    description: 'Optional. The end date (inclusive) for the statistics data range. Accepts ISO 8601 format: yyyy-MM-dd or yyyy-MM-ddTHH:mm:ss.fffZ (Z is optional, always interpreted as UTC). If not provided, defaults to the current date.',
    resource: 'campaign',
    operations: ['getStats'],

  }),

  createField({
    displayName: 'Refresh',
    name: 'refresh',
    type: 'boolean',
    default: false,
    description: 'Whether to force-refresh statistics before retrieval. When true, recalculates all stats, processes A/B test variants, refreshes followups, and clears caches. Defaults to false for faster response times.',
    resource: 'campaign',
    operations: ['getStats'],

  }),

  {
    displayName: 'Additional Fields',
    name: 'additionalFields',
    type: 'collection',
    default: {},
    placeholder: 'Add Field',
    displayOptions: {
      show: { resource: ['campaign'], operation: ['create'] },
    },
    options: [
      { displayName: 'BCC Emails', name: 'bccEmails', type: 'string', default: '' },
      { displayName: 'Body', name: 'body', type: 'string', default: '' },
      { displayName: 'CC Emails', name: 'ccEmails', type: 'string', default: '' },
      { displayName: 'Daily Limit', name: 'dailyLimit', type: 'number', default: 50 },
      { displayName: 'Daily Limit Increase', name: 'dailyLimitIncrease', type: 'boolean', default: false, description: 'Whether to automatically increase the daily sending limit' },
      { displayName: 'Daily Limit Increase Percent', name: 'dailyLimitIncreasePercent', type: 'number', default: 0 },
      { displayName: 'Daily Limit Increase To Max', name: 'dailyLimitIncreaseToMax', type: 'number', default: 0 },
      { displayName: 'Daily Limit Initial', name: 'dailyLimitInitial', type: 'number', default: 0 },
      { displayName: 'Daily Limit Initial Enabled', name: 'dailyLimitInitialEnabled', type: 'boolean', default: false, description: 'Whether to enable the initial daily limit' },
      { displayName: 'Daily Limit On Date', name: 'dailyLimitOnDate', type: 'string', default: '' },
      { displayName: 'Daily Limit Per', name: 'dailyLimitPer', type: 'options', default: 'Sender', options: [{ name: 'Sender', value: 'Sender' }, { name: 'Campaign', value: 'Campaign' }] },
      { displayName: 'Daily Limit Prioritize', name: 'dailyLimitPrioritize', type: 'options', default: 'Initial', options: [{ name: 'Initial', value: 'Initial' }, { name: 'Followup', value: 'Followup' }] },
      { displayName: 'Daily Limit Which Emails Count', name: 'dailyLimitWhichEmailsCount', type: 'options', default: 'All', options: [{ name: 'All', value: 'All' }, { name: 'Initial', value: 'Initial' }] },
      { displayName: 'Deactivate If Missing Placeholder', name: 'deactivateIfMissingPlaceholder', type: 'boolean', default: false, description: 'Whether to deactivate the campaign if a placeholder is missing' },
      { displayName: 'Delay Min Minutes', name: 'delayMinMinutes', type: 'number', default: 30 },
      { displayName: 'Description', name: 'description', type: 'string', default: '' },
      { displayName: 'ESP Limit Enabled', name: 'espLimitEnabled', type: 'boolean', default: false, description: 'Whether to enable ESP-based sending limits' },
      { displayName: 'ESP Limit to Google', name: 'espLimitToGoogle', type: 'boolean', default: false, description: 'Whether to limit sending to Google ESP recipients' },
      { displayName: 'ESP Limit to Microsoft', name: 'espLimitToMicrosoft', type: 'boolean', default: false, description: 'Whether to limit sending to Microsoft ESP recipients' },
      { displayName: 'ESP Limit to Other', name: 'espLimitToOther', type: 'boolean', default: false, description: 'Whether to limit sending to other ESP recipients' },
      { displayName: 'ESP Match Enabled', name: 'espMatchEnabled', type: 'boolean', default: false, description: 'Whether to match prospects to senders by ESP' },
      { displayName: 'ESP Match Type', name: 'espMatchType', type: 'options', default: 'None', options: [{ name: 'None', value: 'None' }, { name: 'MatchSender', value: 'MatchSender' }, { name: 'MatchDomain', value: 'MatchDomain' }] },
      { displayName: 'Folder ID', name: 'folderId', type: 'number', default: 0 },
      { displayName: 'From Emails', name: 'fromEmails', type: 'string', default: '' },
      { displayName: 'From Name', name: 'fromName', type: 'string', default: '' },
      { displayName: 'Prospect Value', name: 'prospectValue', type: 'number', default: 0 },
      { displayName: 'Reply BCC Emails', name: 'replyBccEmails', type: 'string', default: '' },
      { displayName: 'Reply CC Emails', name: 'replyCcEmails', type: 'string', default: '' },
      { displayName: 'Reply To Email', name: 'replyToEmail', type: 'string', default: '' },
      { displayName: 'Schedule Send On Date', name: 'scheduleSendOnDate', type: 'string', default: '' },
      { displayName: 'Schedule Send On Date Enabled', name: 'scheduleSendOnDateEnabled', type: 'boolean', default: false, description: 'Whether to enable scheduled sending on a specific date' },
      { displayName: 'Schedule Send On Date Hours', name: 'scheduleSendOnDateHours', type: 'number', default: 10 },
      { displayName: 'Schedule Send On Date Minutes', name: 'scheduleSendOnDateMinutes', type: 'number', default: 10 },
      { displayName: 'Schedule Sending', name: 'scheduleSending', type: 'boolean', default: false, description: 'Whether to schedule sending within specific hours and days' },
      { displayName: 'Schedule Time Zone', name: 'scheduleTimeZone', type: 'string', default: 'UTC' },
      { displayName: 'Send Fri', name: 'sendFri', type: 'boolean', default: true, description: 'Whether to send emails on Fridays' },
      { displayName: 'Send Fri After', name: 'sendFriAfter', type: 'number', default: 0 },
      { displayName: 'Send Fri Before', name: 'sendFriBefore', type: 'number', default: 0 },
      { displayName: 'Send Mon', name: 'sendMon', type: 'boolean', default: true, description: 'Whether to send emails on Mondays' },
      { displayName: 'Send Mon After', name: 'sendMonAfter', type: 'number', default: 0 },
      { displayName: 'Send Mon Before', name: 'sendMonBefore', type: 'number', default: 0 },
      { displayName: 'Send Sat', name: 'sendSat', type: 'boolean', default: true, description: 'Whether to send emails on Saturdays' },
      { displayName: 'Send Sat After', name: 'sendSatAfter', type: 'number', default: 0 },
      { displayName: 'Send Sat Before', name: 'sendSatBefore', type: 'number', default: 0 },
      { displayName: 'Send Sun', name: 'sendSun', type: 'boolean', default: true, description: 'Whether to send emails on Sundays' },
      { displayName: 'Send Sun After', name: 'sendSunAfter', type: 'number', default: 0 },
      { displayName: 'Send Sun Before', name: 'sendSunBefore', type: 'number', default: 0 },
      { displayName: 'Send Thu', name: 'sendThu', type: 'boolean', default: true, description: 'Whether to send emails on Thursdays' },
      { displayName: 'Send Thu After', name: 'sendThuAfter', type: 'number', default: 0 },
      { displayName: 'Send Thu Before', name: 'sendThuBefore', type: 'number', default: 0 },
      { displayName: 'Send Tue', name: 'sendTue', type: 'boolean', default: true, description: 'Whether to send emails on Tuesdays' },
      { displayName: 'Send Tue After', name: 'sendTueAfter', type: 'number', default: 0 },
      { displayName: 'Send Tue Before', name: 'sendTueBefore', type: 'number', default: 0 },
      { displayName: 'Send Unsubscribe List Header', name: 'sendUnsubscribeListHeader', type: 'boolean', default: false, description: 'Whether to send the unsubscribe list header in emails' },
      { displayName: 'Send Wed', name: 'sendWed', type: 'boolean', default: true, description: 'Whether to send emails on Wednesdays' },
      { displayName: 'Send Wed After', name: 'sendWedAfter', type: 'number', default: 0 },
      { displayName: 'Send Wed Before', name: 'sendWedBefore', type: 'number', default: 0 },
      { displayName: 'Stop Coworkers On Reply', name: 'stopCoworkersOnReply', type: 'boolean', default: false, description: 'Whether to stop sending to coworkers when a reply is received' },
      { displayName: 'Subject', name: 'subject', type: 'string', default: '' },
      { displayName: 'Text Only Emails', name: 'textOnlyEmails', type: 'boolean', default: false, description: 'Whether to send plain-text emails only' },
      { displayName: 'Track Clicks', name: 'trackClicks', type: 'boolean', default: false, description: 'Whether to track email link clicks' },
      { displayName: 'Track Opens', name: 'trackOpens', type: 'boolean', default: false, description: 'Whether to track email opens' },
      { displayName: 'Use Prospects Time Zone', name: 'useProspectsTimeZone', type: 'boolean', default: false, description: 'Whether to send emails according to each prospect\'s local time zone' }
    ],
  },

  {
    displayName: 'Update Fields',
    name: 'updateFields',
    type: 'collection',
    default: {},
    placeholder: 'Add Field',
    displayOptions: {
      show: { resource: ['campaign'], operation: ['update'] },
    },
    options: [
      { displayName: 'BCC Emails', name: 'bccEmails', type: 'string', default: '' },
      { displayName: 'Body', name: 'body', type: 'string', default: '' },
      { displayName: 'CC Emails', name: 'ccEmails', type: 'string', default: '' },
      { displayName: 'Daily Limit', name: 'dailyLimit', type: 'number', default: 0 },
      { displayName: 'Daily Limit Increase', name: 'dailyLimitIncrease', type: 'boolean', default: false, description: 'Whether to automatically increase the daily sending limit' },
      { displayName: 'Daily Limit Increase Percent', name: 'dailyLimitIncreasePercent', type: 'number', default: 0 },
      { displayName: 'Daily Limit Increase To Max', name: 'dailyLimitIncreaseToMax', type: 'number', default: 0 },
      { displayName: 'Daily Limit Initial', name: 'dailyLimitInitial', type: 'number', default: 0 },
      { displayName: 'Daily Limit Initial Enabled', name: 'dailyLimitInitialEnabled', type: 'boolean', default: false, description: 'Whether to enable the initial daily limit' },
      { displayName: 'Daily Limit On Date', name: 'dailyLimitOnDate', type: 'string', default: '' },
      { displayName: 'Daily Limit Per', name: 'dailyLimitPer', type: 'options', default: 'Sender', options: [{ name: 'Sender', value: 'Sender' }, { name: 'Campaign', value: 'Campaign' }] },
      { displayName: 'Daily Limit Prioritize', name: 'dailyLimitPrioritize', type: 'options', default: 'Initial', options: [{ name: 'Initial', value: 'Initial' }, { name: 'Followup', value: 'Followup' }] },
      { displayName: 'Daily Limit Which Emails Count', name: 'dailyLimitWhichEmailsCount', type: 'options', default: 'All', options: [{ name: 'All', value: 'All' }, { name: 'Initial', value: 'Initial' }] },
      { displayName: 'Deactivate If Missing Placeholder', name: 'deactivateIfMissingPlaceholder', type: 'boolean', default: false, description: 'Whether to deactivate the campaign if a placeholder is missing' },
      { displayName: 'Delay Min Minutes', name: 'delayMinMinutes', type: 'number', default: 0 },
      { displayName: 'Description', name: 'description', type: 'string', default: '' },
      { displayName: 'ESP Limit Enabled', name: 'espLimitEnabled', type: 'boolean', default: false, description: 'Whether to enable ESP-based sending limits' },
      { displayName: 'ESP Limit to Google', name: 'espLimitToGoogle', type: 'boolean', default: false, description: 'Whether to limit sending to Google ESP recipients' },
      { displayName: 'ESP Limit to Microsoft', name: 'espLimitToMicrosoft', type: 'boolean', default: false, description: 'Whether to limit sending to Microsoft ESP recipients' },
      { displayName: 'ESP Limit to Other', name: 'espLimitToOther', type: 'boolean', default: false, description: 'Whether to limit sending to other ESP recipients' },
      { displayName: 'ESP Match Enabled', name: 'espMatchEnabled', type: 'boolean', default: false, description: 'Whether to match prospects to senders by ESP' },
      { displayName: 'ESP Match Type', name: 'espMatchType', type: 'options', default: 'None', options: [{ name: 'None', value: 'None' }, { name: 'MatchSender', value: 'MatchSender' }, { name: 'MatchDomain', value: 'MatchDomain' }] },
      { displayName: 'Folder ID', name: 'folderId', type: 'number', default: 0 },
      { displayName: 'From Emails', name: 'fromEmails', type: 'string', default: '' },
      { displayName: 'From Name', name: 'fromName', type: 'string', default: '' },
      { displayName: 'Name', name: 'name', type: 'string', default: '' },
      { displayName: 'Prospect Value', name: 'prospectValue', type: 'number', default: 0 },
      { displayName: 'Reply BCC Emails', name: 'replyBccEmails', type: 'string', default: '' },
      { displayName: 'Reply CC Emails', name: 'replyCcEmails', type: 'string', default: '' },
      { displayName: 'Reply To Email', name: 'replyToEmail', type: 'string', default: '' },
      { displayName: 'Schedule Send On Date', name: 'scheduleSendOnDate', type: 'string', default: '' },
      { displayName: 'Schedule Send On Date Enabled', name: 'scheduleSendOnDateEnabled', type: 'boolean', default: false, description: 'Whether to enable scheduled sending on a specific date' },
      { displayName: 'Schedule Send On Date Hours', name: 'scheduleSendOnDateHours', type: 'number', default: 0 },
      { displayName: 'Schedule Send On Date Minutes', name: 'scheduleSendOnDateMinutes', type: 'number', default: 0 },
      { displayName: 'Schedule Sending', name: 'scheduleSending', type: 'boolean', default: false, description: 'Whether to schedule sending within specific hours and days' },
      { displayName: 'Schedule Time Zone', name: 'scheduleTimeZone', type: 'string', default: '' },
      { displayName: 'Send Fri', name: 'sendFri', type: 'boolean', default: false, description: 'Whether to send emails on Fridays' },
      { displayName: 'Send Fri After', name: 'sendFriAfter', type: 'number', default: 0 },
      { displayName: 'Send Fri Before', name: 'sendFriBefore', type: 'number', default: 0 },
      { displayName: 'Send Mon', name: 'sendMon', type: 'boolean', default: false, description: 'Whether to send emails on Mondays' },
      { displayName: 'Send Mon After', name: 'sendMonAfter', type: 'number', default: 0 },
      { displayName: 'Send Mon Before', name: 'sendMonBefore', type: 'number', default: 0 },
      { displayName: 'Send Sat', name: 'sendSat', type: 'boolean', default: false, description: 'Whether to send emails on Saturdays' },
      { displayName: 'Send Sat After', name: 'sendSatAfter', type: 'number', default: 0 },
      { displayName: 'Send Sat Before', name: 'sendSatBefore', type: 'number', default: 0 },
      { displayName: 'Send Sun', name: 'sendSun', type: 'boolean', default: false, description: 'Whether to send emails on Sundays' },
      { displayName: 'Send Sun After', name: 'sendSunAfter', type: 'number', default: 0 },
      { displayName: 'Send Sun Before', name: 'sendSunBefore', type: 'number', default: 0 },
      { displayName: 'Send Thu', name: 'sendThu', type: 'boolean', default: false, description: 'Whether to send emails on Thursdays' },
      { displayName: 'Send Thu After', name: 'sendThuAfter', type: 'number', default: 0 },
      { displayName: 'Send Thu Before', name: 'sendThuBefore', type: 'number', default: 0 },
      { displayName: 'Send Tue', name: 'sendTue', type: 'boolean', default: false, description: 'Whether to send emails on Tuesdays' },
      { displayName: 'Send Tue After', name: 'sendTueAfter', type: 'number', default: 0 },
      { displayName: 'Send Tue Before', name: 'sendTueBefore', type: 'number', default: 0 },
      { displayName: 'Send Unsubscribe List Header', name: 'sendUnsubscribeListHeader', type: 'boolean', default: false, description: 'Whether to send the unsubscribe list header in emails' },
      { displayName: 'Send Wed', name: 'sendWed', type: 'boolean', default: false, description: 'Whether to send emails on Wednesdays' },
      { displayName: 'Send Wed After', name: 'sendWedAfter', type: 'number', default: 0 },
      { displayName: 'Send Wed Before', name: 'sendWedBefore', type: 'number', default: 0 },
      { displayName: 'Stop Coworkers On Reply', name: 'stopCoworkersOnReply', type: 'boolean', default: false, description: 'Whether to stop sending to coworkers when a reply is received' },
      { displayName: 'Subject', name: 'subject', type: 'string', default: '' },
      { displayName: 'Text Only Emails', name: 'textOnlyEmails', type: 'boolean', default: false, description: 'Whether to send plain-text emails only' },
      { displayName: 'Track Clicks', name: 'trackClicks', type: 'boolean', default: false, description: 'Whether to track email link clicks' },
      { displayName: 'Track Opens', name: 'trackOpens', type: 'boolean', default: false, description: 'Whether to track email opens' },
      { displayName: 'Use Prospects Time Zone', name: 'useProspectsTimeZone', type: 'boolean', default: false, description: 'Whether to send emails according to each prospect\'s local time zone' }
    ],
  },

  createField({
    displayName: 'Prospect',
    name: 'prospectId',
    type: 'resourceLocator',
    default: { mode: 'list', value: '' },
    description: 'Select a prospect from the list or enter its ID',
    resource: 'campaign',
    operations: ['removeProspect'],
    modes: [
      {
        displayName: 'From list',
        name: 'list',
        type: 'list',
        placeholder: 'Select a prospect...',
        typeOptions: {
          searchListMethod: 'searchProspects',
          searchable: true,
          searchFilterRequired: false,
        },
      },
      {
        displayName: 'By ID',
        name: 'id',
        type: 'string',
        placeholder: 'e.g. 1234',
        validation: [
          {
            type: 'regex',
            properties: {
              regex: '^\\d+$',
              errorMessage: 'Only numeric IDs are allowed',
            },
          },
        ],
      },
    ],
  }),

  createField({
    displayName: 'Tag',
    name: 'tagId',
    type: 'resourceLocator',
    default: { mode: 'list', value: '' },
    description: 'Select a tag from the list or enter its ID',
    resource: 'campaign',
    operations: ['addTag', 'removeTag'],
    modes: [
      {
        displayName: 'From list',
        name: 'list',
        type: 'list',
        placeholder: 'Select a tag...',
        typeOptions: {
          searchListMethod: 'searchTags',
          searchable: true,
          searchFilterRequired: false,
        },
      },
      {
        displayName: 'By ID',
        name: 'id',
        type: 'string',
        placeholder: 'e.g. 1234',
        validation: [
          {
            type: 'regex',
            properties: {
              regex: '^\\d+$',
              errorMessage: 'Only numeric IDs are allowed',
            },
          },
        ],
      },
    ],
  }),
];
