import { INodeProperties } from 'n8n-workflow';
import { createField } from './common/fields';

export const senderOperations: INodeProperties[] = [
    createField({
        displayName: 'Operation',
        name: 'operation',
        type: 'options',
								noDataExpression: true,
        resource: 'sender',
        default: '',
        optionsList: [
            { name: 'Get Many', value: 'getMany', action: 'Get many senders', description: 'Retrieve a list of senders' },
            { name: 'Create', value: 'create', action: 'Create sender', description: 'Create a new sender' },
            { name: 'Get', value: 'getById', action: 'Get sender', description: 'Retrieve a sender' },
            { name: 'Delete', value: 'delete', action: 'Delete sender', description: 'Delete a sender permanently' },
            { name: 'Update', value: 'update', action: 'Update sender', description: 'Update a sender' },
            { name: 'Get Errors', value: 'getErrors', action: 'Get sender authentication errors', description: 'Retrieve DKIM, SPF, and DMARC authentication errors for a sender' }
        ],
    }),
];

export const senderFields: INodeProperties[] = [

    createField({
        displayName: 'Sender',
        name: 'senderId',
        type: 'resourceLocator',
        default: { mode: 'list', value: '' },
        description: 'Select a sender from the list or enter its ID',
        resource: 'sender',
        operations: ['getById', 'update', 'delete', 'getErrors'],
        modes: [
            {
                displayName: 'From list',
                name: 'list',
                type: 'list',
                placeholder: 'Select a sender...',
                typeOptions: {
                    searchListMethod: 'searchSenders',
                    searchable: true,
                    searchFilterRequired: false,
                },
            },
            {
                displayName: 'By ID',
                name: 'id',
                type: 'string',
                placeholder: 'e.g. 1234',
                validation: [
                    {
                        type: 'regex',
                        properties: {
                            regex: '^\\\\d+$',
                            errorMessage: 'Only numeric IDs are allowed',
                        },
                    },
                ],
            },
        ],
    }),

    createField({
        displayName: 'Page',
        name: 'page',
        type: 'number',
        default: 1,
        resource: 'sender',
        operations: ['getMany'],
    }),

    createField({
        displayName: 'Limit',
        name: 'limit',
        type: 'number',
								typeOptions: {
									minValue: 1,
								},
								description: 'Max number of results to return',
        default: 50,
        resource: 'sender',
        operations: ['getMany'],
    }),

    createField({
        displayName: 'Folder',
        name: 'folder',
        type: 'string',
        default: '',
        description: 'Filter by folder name',
        resource: 'sender',
        operations: ['getMany'],
    }),

    createField({
        displayName: 'Status',
        name: 'status',
        type: 'string',
        default: '',
        description: 'Filter by status (e.g., "error")',
        resource: 'sender',
        operations: ['getMany'],
    }),

    createField({
        displayName: 'Warmup',
        name: 'warmup',
        type: 'boolean',
        default: false,
        description: 'Whether to filter by warmup status',
        resource: 'sender',
        operations: ['getMany'],
    }),

    createField({
        displayName: 'Search',
        name: 'search',
        type: 'string',
        default: '',
        description: 'Search by text (first/last/email)',
        resource: 'sender',
        operations: ['getMany'],
    }),

    createField({
        displayName: 'Starting After',
        name: 'startingAfter',
        type: 'number',
        default: 0,
        description: 'Cursor for next page (optional, for cursor-based pagination)',
        resource: 'sender',
        operations: ['getMany'],
    }),

    createField({
        displayName: 'Simplify',
        name: 'simplify',
        type: 'boolean',
        default: true,
        description: 'Whether to return a simplified version of the response instead of the raw data',
        resource: 'sender',
        operations: ['getMany'],
    }),

    createField({
        displayName: 'Email',
        name: 'email',
        type: 'string',
								placeholder: 'e.g. nathan@example.com',
        default: '',
        description: 'Email address of the sender account used for outgoing campaigns; must be valid email format with maximum 100 characters',
        resource: 'sender',
        operations: ['create'],
        required: true,
    }),

    createField({
        displayName: 'Daily Limit',
        name: 'dailyLimit',
        type: 'number',
        default: 0,
        description: 'Maximum number of emails this sender can send per day; must be between 1 and 10,000',
        resource: 'sender',
        operations: ['create'],
        required: true,
    }),

    createField({
        displayName: 'Custom SMTP Server',
        name: 'customSmtpServer',
        type: 'string',
        default: '',
        description: 'SMTP server hostname for custom email sending configuration; maximum 128 characters',
        placeholder: 'e.g. smtp.gmail.com',
        resource: 'sender',
        operations: ['create'],
        required: true,
    }),

    createField({
        displayName: 'Custom SMTP Port',
        name: 'customSmtpPort',
        type: 'number',
        default: 0,
        description: 'SMTP server port number for custom email sending configuration',
        resource: 'sender',
        operations: ['create'],
        required: true,
    }),

    createField({
        displayName: 'Custom SMTP Password',
        name: 'customSmtpPass',
        type: 'string',
        default: '',
        description: 'Password for custom SMTP server authentication; maximum 256 characters, stored securely',
        resource: 'sender',
        operations: ['create'],
        required: true,
    }),

    createField({
        displayName: 'Custom IMAP Server',
        name: 'customImapServer',
        type: 'string',
        default: '',
        description: 'IMAP server hostname for custom email retrieval configuration; maximum 128 characters',
        placeholder: 'e.g. imap.gmail.com',
        resource: 'sender',
        operations: ['create'],
        required: true,
    }),

    createField({
        displayName: 'Custom IMAP Port',
        name: 'customImapPort',
        type: 'string',
        default: '',
        description: 'IMAP server port number for custom email retrieval configuration; typically 993 for SSL/TLS; maximum 64 characters',
        resource: 'sender',
        operations: ['create'],
        required: true,
    }),

    createField({
        displayName: 'Custom IMAP Password',
        name: 'customImapPass',
        type: 'string',
        default: '',
        description: 'Password for custom IMAP server authentication; maximum 256 characters, stored securely',
        resource: 'sender',
        operations: ['create'],
        required: true,
    }),

    {
        displayName: 'Additional Fields',
        name: 'additionalFields',
        type: 'collection',
        default: {},
        placeholder: 'Add Field',
        displayOptions: {
            show: { resource: ['sender'], operation: ['create'] },
        },
        options: [
            { displayName: 'Custom IMAP Username', name: 'customImapUsername', type: 'string', default: '' },
            { displayName: 'Custom SMTP Username', name: 'customSmtpUsername', type: 'string', default: '' },
            { displayName: 'Custom Warmup Tag', name: 'customWarmupTag', type: 'string', default: '' },
            { displayName: 'Daily Limit Increase', name: 'dailyLimitIncrease', type: 'boolean', default: false, description: 'Whether to automatically increase the daily sending limit' },
            { displayName: 'Daily Limit Increase Percent', name: 'dailyLimitIncreasePercent', type: 'number', default: 0 },
            { displayName: 'Daily Limit Increase To Max', name: 'dailyLimitIncreaseToMax', type: 'number', default: 0 },
            { displayName: 'Delay Min', name: 'delayMin', type: 'number', default: 0 },
            { displayName: 'First Name', name: 'firstName', type: 'string', default: '' },
            { displayName: 'Folder', name: 'folder', type: 'string', default: '' },
            { displayName: 'From Name', name: 'fromName', type: 'string', default: '' },
            { displayName: 'Last Name', name: 'lastName', type: 'string', default: '' },
            { displayName: 'Reply To', name: 'replyTo', type: 'string', default: '' },
            { displayName: 'Sender Custom1', name: 'senderCustom1', type: 'string', default: '' },
            { displayName: 'Sender Custom10', name: 'senderCustom10', type: 'string', default: '' },
            { displayName: 'Sender Custom2', name: 'senderCustom2', type: 'string', default: '' },
            { displayName: 'Sender Custom3', name: 'senderCustom3', type: 'string', default: '' },
            { displayName: 'Sender Custom4', name: 'senderCustom4', type: 'string', default: '' },
            { displayName: 'Sender Custom5', name: 'senderCustom5', type: 'string', default: '' },
            { displayName: 'Sender Custom6', name: 'senderCustom6', type: 'string', default: '' },
            { displayName: 'Sender Custom7', name: 'senderCustom7', type: 'string', default: '' },
            { displayName: 'Sender Custom8', name: 'senderCustom8', type: 'string', default: '' },
            { displayName: 'Sender Custom9', name: 'senderCustom9', type: 'string', default: '' },
            { displayName: 'Signature', name: 'signature', type: 'string', default: '' },
            { displayName: 'Tracking Domain', name: 'trackingDomain', type: 'string', default: '' },
            { displayName: 'Warmup', name: 'warmup', type: 'boolean', default: false, description: 'Whether warmup is enabled for this sender' },
            { displayName: 'Warmup Daily Limit', name: 'warmupDailyLimit', type: 'number', default: 0 },
            { displayName: 'Warmup Daily Limit Increase', name: 'warmupDailyLimitIncrease', type: 'boolean', default: false, description: 'Whether to automatically increase the warmup daily limit' },
            { displayName: 'Warmup Daily Limit Increase Percent', name: 'warmupDailyLimitIncreasePercent', type: 'number', default: 0 },
            { displayName: 'Warmup Daily Limit Increase To Max', name: 'warmupDailyLimitIncreaseToMax', type: 'number', default: 0 },
            { displayName: 'Warmup Reply Percent', name: 'warmupReplyPercent', type: 'number', default: 0 },
            { displayName: 'Warmup Skip Weekends', name: 'warmupSkipWeekends', type: 'boolean', default: false, description: 'Whether to skip weekends during the warmup period' }
        ],
    },

    {
        displayName: 'Update Fields',
        name: 'updateFields',
        type: 'collection',
        default: {},
        placeholder: 'Add Field',
        displayOptions: {
            show: { resource: ['sender'], operation: ['update'] },
        },
        options: [
            { displayName: 'Custom IMAP Password', name: 'customImapPass', type: 'string', default: '' },
            { displayName: 'Custom IMAP Port', name: 'customImapPort', type: 'string', default: '' },
            { displayName: 'Custom IMAP Server', name: 'customImapServer', type: 'string', default: '' },
            { displayName: 'Custom IMAP Username', name: 'customImapUsername', type: 'string', default: '' },
            { displayName: 'Custom SMTP Password', name: 'customSmtpPass', type: 'string', default: '' },
            { displayName: 'Custom SMTP Port', name: 'customSmtpPort', type: 'number', default: 0 },
            { displayName: 'Custom SMTP Server', name: 'customSmtpServer', type: 'string', default: '' },
            { displayName: 'Custom SMTP Username', name: 'customSmtpUsername', type: 'string', default: '' },
            { displayName: 'Custom Warmup Tag', name: 'customWarmupTag', type: 'string', default: '' },
            { displayName: 'Daily Limit', name: 'dailyLimit', type: 'number', default: 0 },
            { displayName: 'Daily Limit Increase', name: 'dailyLimitIncrease', type: 'boolean', default: false, description: 'Whether to automatically increase the daily sending limit' },
            { displayName: 'Daily Limit Increase Percent', name: 'dailyLimitIncreasePercent', type: 'number', default: 0 },
            { displayName: 'Daily Limit Increase To Max', name: 'dailyLimitIncreaseToMax', type: 'number', default: 0 },
            { displayName: 'Delay Min', name: 'delayMin', type: 'number', default: 0 },
            { displayName: 'First Name', name: 'firstName', type: 'string', default: '' },
            { displayName: 'Folder', name: 'folder', type: 'string', default: '' },
            { displayName: 'From Name', name: 'fromName', type: 'string', default: '' },
            { displayName: 'Last Name', name: 'lastName', type: 'string', default: '' },
            { displayName: 'Reply To', name: 'replyTo', type: 'string', default: '' },
            { displayName: 'Sender Custom1', name: 'senderCustom1', type: 'string', default: '' },
            { displayName: 'Sender Custom10', name: 'senderCustom10', type: 'string', default: '' },
            { displayName: 'Sender Custom2', name: 'senderCustom2', type: 'string', default: '' },
            { displayName: 'Sender Custom3', name: 'senderCustom3', type: 'string', default: '' },
            { displayName: 'Sender Custom4', name: 'senderCustom4', type: 'string', default: '' },
            { displayName: 'Sender Custom5', name: 'senderCustom5', type: 'string', default: '' },
            { displayName: 'Sender Custom6', name: 'senderCustom6', type: 'string', default: '' },
            { displayName: 'Sender Custom7', name: 'senderCustom7', type: 'string', default: '' },
            { displayName: 'Sender Custom8', name: 'senderCustom8', type: 'string', default: '' },
            { displayName: 'Sender Custom9', name: 'senderCustom9', type: 'string', default: '' },
            { displayName: 'Signature', name: 'signature', type: 'string', default: '' },
            { displayName: 'Tracking Domain', name: 'trackingDomain', type: 'string', default: '' },
            { displayName: 'Warmup', name: 'warmup', type: 'boolean', default: false, description: 'Whether warmup is enabled for this sender' },
            { displayName: 'Warmup Daily Limit', name: 'warmupDailyLimit', type: 'number', default: 0 },
            { displayName: 'Warmup Daily Limit Increase', name: 'warmupDailyLimitIncrease', type: 'boolean', default: false, description: 'Whether to automatically increase the warmup daily limit' },
            { displayName: 'Warmup Daily Limit Increase Percent', name: 'warmupDailyLimitIncreasePercent', type: 'number', default: 0 },
            { displayName: 'Warmup Daily Limit Increase To Max', name: 'warmupDailyLimitIncreaseToMax', type: 'number', default: 0 },
            { displayName: 'Warmup Reply Percent', name: 'warmupReplyPercent', type: 'number', default: 0 },
            { displayName: 'Warmup Skip Weekends', name: 'warmupSkipWeekends', type: 'boolean', default: false, description: 'Whether to skip weekends during the warmup period' }
        ],
    },
];
